# Header
menu:
  Home: /
  历史文章: /archives
  GitHub: https://github.com/jayxhj
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- tagcloud
- archive
- links

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true
format: YYYY 年 MM 月

# Miscellaneous
google_analytics: UA-27843739-2
baidu_analytics: true
favicon: /favicon.png
twitter: jayxhj
google_plus:
fb_admins:
fb_app_id:

# Links
links:
  顺流而下，把梦做完。: http://ceix.me/
  嗨军: http://likangjun.com/
  张辉|Ecli2h: http://www.ecli2h.net/
